version: '2'
services:
  eureka-server:
    hostname: eureka-server
    image: eureka-server
    ports:
      - "8761:8761"

  book-info-service:
    image: book-info-service
    links:
      - "eureka-server"
    ports:
      - "8082:8082"

  rating-data-service:
    image: rating-data-service
    links:
      - "eureka-server"
    ports:
      - "8083:8083"

  book-catalog-service:
    image: book-catalog-service
    links:
      - "eureka-server"
    ports:
      - "8081:8081"
