spring:
  profiles: docker
  application:
    name: book-catalog-service

server:
  port: 8081

eureka:
  instance:
    hostname: book-catalog-service
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

feign:
  client:
    config:
      default:
        connect-timeout: 100000
        read-timeout: 100000