spring:
  application:
    name: book-catalog-service

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connect-timeout: 100000
        read-timeout: 100000