spring:
  #profiles: docker
  application:
    name: book-catalog-service

server:
  port: 8081

eureka:
  instance:
    hostname: localhost
    #hostname: book-catalog-service
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://eureka-server:8761/eureka/

feign:
  client:
    config:
      default:
        connect-timeout: 999999
        read-timeout: 999999

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false