spring:
  #profiles: docker
  application:
    name: book-info-service

server:
  port: 8082

eureka:
  instance:
    hostname: localhost
    #hostname: book-info-service
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://eureka-server:8761/eureka/