spring:
  #profiles: docker
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    #hostname: eureka-server
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 90
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://eureka-server:8761/eureka/
  server:
    enable-self-preservation: false

zuul:
  prefix: /api
  routes:
    book-catalog-service:
      path: /book-catalog-service/**
      service-id: book-catalog-service
    book-info-service:
      path: /book-info-service/**
      service-id: book-info-service
    rating-data-service:
      path: /rating-data-service/**
      service-id: rating-data-service
  host:
    socket-timeout-millis: 999999
    connect-timeout-millis: 999999

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 999999

ribbon:
  ReadTimeout: 99999
  ConnectTimeout: 99999
