spring:
  profiles: docker
  application:
    name: rating-data-service

server:
  port: 8083

eureka:
  instance:
    hostname: rating-data-service
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/